autotest:
  browser:
    chrome:
      arguments:
        - --headless
        - --no-sandbox
        - --disable-gpu
        - --disable-dev-shm-usage
        - disable-infobars
        - --disable-extensions
